name: Check coding style
on: push

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check coding style
        run: check.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.EPITECH_TOKEN }}
