name: Coding style

on: push

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check Coding Style
        run: check.sh echo "$PWD $PWD"
      - name: Display Errors
