name: Check coding style
on: push

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check coding style
        run: check.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}
      - name: Check report
        if: always()
        run: |
          if [ -s "${GITHUB_WORKSPACE}/coding-style-reports.log" ]; then
            echo "Coding style errors detected"
            exit 1
          else
            echo "No coding style errors detected"
          fi
