name: Coding style

on: push

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check Coding Style
        working-directory: ${{ github.workspace }}
        run: check.sh . .
      - name: Check Coding Style Errors
        run: |
          if [ -s coding-style-error.log ]; then
            echo "Coding style check failed"
            exit 1
          else
            echo "Coding style check passed"
          fi
