name: Repository Mirroring

on:
  push:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Mirror Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        source_repo: "Fizo55/workflow_epitech"
        destination_repo: "EpitechPromo2027/B-DOP-200-NAN-2-1-bschocolatine-erwann.tanguy"
        destination_token: ${{ secrets.EPITECH_TOKEN }}
